# Generated by Django 4.0.1 on 2022-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('subscription_date', models.DateField()),
            ],
        ),
    ]
