# Generated by Django 4.0.1 on 2022-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
